services:
    librespeed:
        image: lscr.io/linuxserver/librespeed:latest
        container_name: librespeed
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        ports:
            - "8080:80"
        restart: unless-stopped
