services:
    librespeed:
        image: lscr.io/linuxserver/librespeed:latest
        container_name: librespeed
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - VIRTUAL_HOST=10.65.16.8  # Replace with your domain or IP
            - LETSENCRYPT_HOST=10.65.16.8
            - LETSENCRYPT_EMAIL=emendieta90@gmail.com
        expose:
            - "80"
        networks:
            - proxy
        restart: unless-stopped

    nginx:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        environment:
            - 10.65.16.8
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ~/certs/librespeed.crt:/etc/nginx/certs/librespeed.crt
            - ~/certs/librespeed.key:/etc/nginx/certs/librespeed.key
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /etc/nginx/certs:/etc/nginx/certs
            - /etc/nginx/vhost.d:/etc/nginx/vhost.d
            - ${HOME}/nginx-html:/usr/share/nginx/html
        networks:
            - proxy
        restart: unless-stopped

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/nginx/certs:/etc/nginx/certs
        networks:
            - proxy
        restart: unless-stopped

networks:
    proxy:
        external: true
